services:

  # ============== [Dev] ==============

  backend-dev:
    image: backend-search-dev:latest
    build: ./backend
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      sh -c "
        python -m uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 8080
      "
    profiles:
      - dev
    volumes:
      - .:/app

  frontend-dev:
    image: frontend-search-dev:latest
    build: ./frontend
    restart: on-failure
    ports:
      - "127.0.0.1:80:80"

  # ============== [Prod] ==============

  backend-prod:
    image: app-test-dev:latest
    build: ./backend
    restart: on-failure
    expose:
      - "8080"
    command: >
      sh -c "
        python -m uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 8080
      "
    volumes:
      - .:/app
    environment:
      - VIRTUAL_HOST=justcheckinghow.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=justcheckinghow.com
    profiles:
      - prod

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "${DOCKER_EGRESS_IP}:80:80"
      - "${DOCKER_EGRESS_IP}:443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - static:/var/www/backend/static
    restart: always
    profiles:
      - prod

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: >
      -notify-sighup nginx-proxy
      -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./egress.nginx.conf:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    profiles:
      - prod

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - DEFAULT_EMAIL=${PROXY_MAIL}
      - DEBUG=1
    restart: always
    profiles:
      - prod

volumes:
  static:
  conf:
  vhost:
  html:
  certs:
  acme:
