SKILLS = [
    "archeologia",
    "nauki prawne",
    "nauki medyczne",
    "filozofia",
    "technologia żywności i żywienia",
    "literaturoznawstwo",
    "ekonomia i finanse",
    "stosunki międzynarodowe",
    "nauki o sztuce",
    "inżynieria lądowa i transport",
    "nauki chemiczne",
    "rolnictwo i ogrodnictwo",
    "nauki o polityce i administracji",
    "nauki o kulturze i religii",
    "nauki biologiczne",
    "automatyka, elektronika i elektrotechnika",
    "biologia medyczna",
    "prawo kanoniczne",
    "inżynieria materiałowa",
    "historia",
    "inżynieria chemiczna",
    "nauki o bezpieczeństwie",
    "nauki o Ziemi i środowisku",
    "zootechnika i rybactwo",
    "nauki fizyczne",
    "architektura i urbanistyka",
    "pedagogika",
    "nauki teologiczne",
    "inżynieria biomedyczna",
    "nauki o zarządzaniu i jakości",
    "matematyka",
    "geografia społeczno-ekonomiczna i gospodarka przestrzenna",
    "nauki socjologiczne",
    "językoznawstwo",
    "nauki o kulturze fizycznej",
    "astronomia",
    "sztuki muzyczne",
    "nauki o zdrowiu",
    "sztuki plastyczne i konserwacja dzieł sztuki",
    "weterynaria",
    "inżynieria bezpieczeństwa",
    "informatyka techniczna i telekomunikacja",
    "inżynieria mechaniczna",
    "psychologia",
    "inżynieria lądowa, geodezja i transport",
    "sztuki filmowe i teatralne",
    "inżynieria środowiska, górnictwo i energetyka",
    "nauki o komunikacji społecznej i mediach",
    "nauki leśne",
    "nauki farmaceutyczne",
    "informatyka",
    "biotechnologia",
    "automatyka, elektronika, elektrotechnika i technologie kosmiczne",
]

PROFESSIONS = [
    "Artist", "Art teacher", "Art therapist",
    "Illustrator", "Graphic designer",
    "Sculptor", "Art instructor",
    "Photographer", "Photojournalist", "Graphic designer",
    "Knitwear designer", "Textile designer",
    "Crochet designer", "Textile designer",
    "Quilter", "Textile designer",
    "Embroidery artist", "Textile designer",
    "Origami artist", "Art instructor",
    "Jewelry designer", "Silversmith",
    "Carpenter", "Furniture designer",
    "Leatherworker", "Leather craftsman",
    "Calligrapher", "Graphic designer",
    "Paper artist", "Art instructor",
    "Scrapbook designer", "Craft instructor",
    "Candle maker", "Craft instructor",
    "Soap maker", "Craft instructor",
    "Gardener", "Landscape designer",
    "Bonsai artist", "Landscape designer",
    "Floral designer", "Florist",
    "Terrarium designer", "Botanist",
    "Baker", "Pastry chef",
    "Chef", "Culinary instructor",
    "Brewmaster", "Brewery owner",
    "Sommelier", "Wine educator",
    "Fermentation specialist", "Food scientist",
    "Mixologist", "Bartender",
    "Tea sommelier", "Tea shop owner",
    "Coffee roaster", "Barista",
    "Park ranger", "Outdoor guide",
    "Outdoor guide", "Camping equipment sales",
    "Fisherman", "Fishing guide",
    "Hunter", "Wildlife manager",
    "Ornithologist", "Bird guide",
    "Rock climbing instructor", "Adventure guide",
    "Mountaineering guide", "Adventure guide",
    "Cyclist", "Bike shop owner",
    "Athlete", "Running coach",
    "Yoga instructor", "Yoga studio owner",
    "Pilates instructor", "Fitness studio owner",
    "Zumba instructor", "Fitness studio owner",
    "Dancer", "Dance instructor",
    "Gymnast", "Gymnastics coach",
    "Martial arts instructor", "Self-defense instructor",
    "Fencer", "Fencing coach",
    "Archery instructor", "Archery range owner",
    "Kayak instructor", "Outdoor guide",
    "Canoe instructor", "Outdoor guide",
    "Surfing instructor", "Surf shop owner",
    "Paddleboarding instructor", "Outdoor guide",
    "Snorkeling instructor", "Outdoor guide",
    "Scuba diving instructor", "Dive shop owner",
    "Ski instructor", "Ski resort manager",
    "Snowboarding instructor", "Ski resort manager",
    "Ice skating instructor", "Ice rink manager",
    "Skateboarding instructor", "Skate shop owner",
    "Parkour instructor", "Parkour gym owner",
    "Equestrian instructor", "Stable owner",
    "Horse trainer", "Equine facility manager",
    "Dog trainer", "Dog obedience school owner",
    "Pet groomer", "Pet grooming salon owner",
    "Pet photographer", "Pet photography studio owner",
    "Animal caretaker", "Pet care business owner",
    "Beekeeper", "Honey producer",
    "Preservationist", "Preserved foods producer",
    "Professional organizer", "Home organization consultant",
    "Interior decorator", "Interior design consultant",
    "DIY home improvement enthusiast", "Home improvement blogger",
    "Furniture restorer", "Antique furniture shop owner",
    "Model builder", "Modeling enthusiast",
    "RC vehicle enthusiast", "RC hobby shop owner",
    "Astronomer", "Stargazing tour guide",
    "Astronomer", "Astronomy educator",
    "Meteorologist", "Weather forecaster",
    "Geocacher", "Geocaching event organizer",
    "Genealogist", "Genealogy consultant",
    "Scrap metal artist", "Art exhibit curator",
    "Poet", "Poetry teacher",
    "Writer", "Creative writing instructor",
    "Journalist", "Writing coach",
    "Blogger", "Content creator",
    "Fiction writer", "Creative writing instructor",
    "Librarian", "Bookstore owner",
    "Book club organizer", "Literary event coordinator",
    "Film photographer", "Photography instructor",
    "Filmmaker", "Film production manager",
    "Video editor", "Video production specialist",
    "Podcaster", "Podcast producer",
    "Graphic designer", "Design agency owner",
    "Music producer", "Music studio owner",
    "DJ", "Event DJ",
    "Musician", "Music teacher",
    "Singer", "Vocal coach",
    "Actor", "Acting coach",
    "Stand-up comedian", "Comedy club owner",
    "Magician", "Magic show organizer",
    "Board game designer", "Board game cafe owner",
    "Card game enthusiast", "Card game tournament organizer",
    "Chess player", "Chess club organizer"
]

HOBBIES_TO_PROFESSIONS = {
    "Painting": ["Artist", "Art teacher", "Art therapist"],
    "Drawing": ["Artist", "Illustrator", "Graphic designer"],
    "Sculpting": ["Sculptor", "Art instructor"],
    "Photography": ["Photographer", "Photojournalist", "Graphic designer"],
    "Knitting": ["Knitwear designer", "Textile designer"],
    "Crocheting": ["Crochet designer", "Textile designer"],
    "Quilting": ["Quilter", "Textile designer"],
    "Embroidery": ["Embroidery artist", "Textile designer"],
    "Origami": ["Origami artist", "Art instructor"],
    "Jewelry making": ["Jewelry designer", "Silversmith"],
    "Woodworking": ["Carpenter", "Furniture designer"],
    "Leatherworking": ["Leatherworker", "Leather craftsman"],
    "Calligraphy": ["Calligrapher", "Graphic designer"],
    "Paper crafting": ["Paper artist", "Art instructor"],
    "Scrapbooking": ["Scrapbook designer", "Craft instructor"],
    "Candle making": ["Candle maker", "Craft instructor"],
    "Soap making": ["Soap maker", "Craft instructor"],
    "Gardening": ["Gardener", "Landscape designer"],
    "Bonsai": ["Bonsai artist", "Landscape designer"],
    "Flower arranging": ["Floral designer", "Florist"],
    "Terrarium building": ["Terrarium designer", "Botanist"],
    "Baking": ["Baker", "Pastry chef"],
    "Cooking": ["Chef", "Culinary instructor"],
    "Hiking": ["Park ranger", "Outdoor guide"],
    "Camping": ["Outdoor guide", "Camping equipment sales"],
    "Fishing": ["Fisherman", "Fishing guide"],
    "Hunting": ["Hunter", "Wildlife manager"],
    "Birdwatching": ["Ornithologist", "Bird guide"],
    "Rock climbing": ["Rock climbing instructor", "Adventure guide"],
    "Mountaineering": ["Mountaineering guide", "Adventure guide"],
    "Cycling": ["Cyclist", "Bike shop owner"],
    "Running": ["Athlete", "Running coach"],
    "Yoga": ["Yoga instructor", "Yoga studio owner"],
    "Pilates": ["Pilates instructor", "Fitness studio owner"],
    "Zumba": ["Zumba instructor", "Fitness studio owner"],
    "Dance": ["Dancer", "Dance instructor"],
    "Gymnastics": ["Gymnast", "Gymnastics coach"],
    "Martial arts": ["Martial arts instructor", "Self-defense instructor"],
    "Fencing": ["Fencer", "Fencing coach"],
    "Archery": ["Archery instructor", "Archery range owner"],
    "Kayaking": ["Kayak instructor", "Outdoor guide"],
    "Canoeing": ["Canoe instructor", "Outdoor guide"],
    "Surfing": ["Surfing instructor", "Surf shop owner"],
    "Paddleboarding": ["Paddleboarding instructor", "Outdoor guide"],
    "Snorkeling": ["Snorkeling instructor", "Outdoor guide"],
    "Scuba diving": ["Scuba diving instructor", "Dive shop owner"],
    "Skiing": ["Ski instructor", "Ski resort manager"],
    "Snowboarding": ["Snowboarding instructor", "Ski resort manager"],
    "Ice skating": ["Ice skating instructor", "Ice rink manager"],
    "Skateboarding": ["Skateboarding instructor", "Skate shop owner"],
    "Parkour": ["Parkour instructor", "Parkour gym owner"],
    "Horseback riding": ["Equestrian instructor", "Stable owner"],
    "Horse training": ["Horse trainer", "Equine facility manager"],
    "Dog training": ["Dog trainer", "Dog obedience school owner"],
    "Pet grooming": ["Pet groomer", "Pet grooming salon owner"],
    "Pet photography": ["Pet photographer", "Pet photography studio owner"],
    "Animal care": ["Animal caretaker", "Pet care business owner"],
    "Beekeeping": ["Beekeeper", "Honey producer"],
    "Canning and preserving": ["Preservationist", "Preserved foods producer"],
    "Home organization": ["Professional organizer", "Home organization consultant"],
    "Interior decorating": ["Interior decorator", "Interior design consultant"],
    "DIY home improvement": ["DIY home improvement enthusiast", "Home improvement blogger"],
    "Furniture restoration": ["Furniture restorer", "Antique furniture shop owner"],
    "Model building": ["Model builder", "Modeling enthusiast"],
    "RC vehicles": ["RC vehicle enthusiast", "RC hobby shop owner"],
    "Stargazing": ["Astronomer", "Stargazing tour guide"],
    "Astronomy": ["Astronomer", "Astronomy educator"],
    "Meteorology": ["Meteorologist", "Weather forecaster"],
    "Geocaching": ["Geocacher", "Geocaching event organizer"],
    "Genealogy": ["Genealogist", "Genealogy consultant"],
    "Scrap metal art": ["Scrap metal artist", "Art exhibit curator"],
    "Poetry writing": ["Poet", "Poetry teacher"],
    "Creative writing": ["Writer", "Creative writing instructor"],
    "Journaling": ["Journalist", "Writing coach"],
    "Blogging": ["Blogger", "Content creator"],
    "Fiction writing": ["Fiction writer", "Creative writing instructor"],
    "Reading": ["Librarian", "Bookstore owner"],
    "Book club participation": ["Book club organizer", "Literary event coordinator"],
    "Film photography": ["Film photographer", "Photography instructor"],
    "Film making": ["Filmmaker", "Film production manager"],
    "Video editing": ["Video editor", "Video production specialist"],
    "Podcasting": ["Podcaster", "Podcast producer"],
    "Graphic design": ["Graphic designer", "Design agency owner"],
    "Music production": ["Music producer", "Music studio owner"],
    "DJing": ["DJ", "Event DJ"],
    "Playing an instrument (e.g., piano, guitar, violin)": ["Musician", "Music teacher"],
    "Singing": ["Singer", "Vocal coach"],
    "Acting": ["Actor", "Acting coach"],
    "Stand-up comedy": ["Stand-up comedian", "Comedy club owner"],
    "Magic tricks": ["Magician", "Magic show organizer"],
    "Board games": ["Board game designer", "Board game cafe owner"],
    "Card games": ["Card game enthusiast", "Card game tournament organizer"],
    "Chess": ["Chess player", "Chess club organizer"]
}

HOBBIES = [
    "Painting",
    "Drawing",
    "Sculpting",
    "Pottery",
    "Photography",
    "Knitting",
    "Crocheting",
    "Quilting",
    "Embroidery",
    "Origami",
    "Jewelry making",
    "Woodworking",
    "Leatherworking",
    "Calligraphy",
    "Paper crafting",
    "Scrapbooking",
    "Candle making",
    "Soap making",
    "Gardening",
    "Bonsai",
    "Flower arranging",
    "Terrarium building",
    "Baking",
    "Cooking",
    "Homebrewing",
    "Wine tasting",
    "Fermentation",
    "Mixology",
    "Brewing tea",
    "Coffee roasting",
    "Hiking",
    "Camping",
    "Fishing",
    "Hunting",
    "Birdwatching",
    "Rock climbing",
    "Mountaineering",
    "Cycling",
    "Running",
    "Yoga",
    "Pilates",
    "Zumba",
    "Dance",
    "Gymnastics",
    "Martial arts",
    "Fencing",
    "Archery",
    "Kayaking",
    "Canoeing",
    "Surfing",
    "Paddleboarding",
    "Snorkeling",
    "Scuba diving",
    "Skiing",
    "Snowboarding",
    "Ice skating",
    "Skateboarding",
    "Parkour",
    "Horseback riding",
    "Horse training",
    "Dog training",
    "Pet grooming",
    "Pet photography",
    "Animal care",
    "Beekeeping",
    "Canning and preserving",
    "Home organization",
    "Interior decorating",
    "DIY home improvement",
    "Furniture restoration",
    "Model building",
    "RC vehicles",
    "Stargazing",
    "Astronomy",
    "Meteorology",
    "Geocaching",
    "Genealogy",
    "Scrap metal art",
    "Poetry writing",
    "Creative writing",
    "Journaling",
    "Blogging",
    "Fiction writing",
    "Reading",
    "Book club participation",
    "Film photography",
    "Film making",
    "Video editing",
    "Podcasting",
    "Graphic design",
    "Music production",
    "DJing",
    "Playing an instrument (e.g., piano, guitar, violin)",
    "Singing",
    "Acting",
    "Stand-up comedy",
    "Magic tricks",
    "Board games",
    "Card games",
    "Chess"
]

CITIES = [
    "Bartoszyce",
    "Bełchatów",
    "Biała Podlaska",
    "Białystok",
    "Bielsko-Biała",
    "Braniewo",
    "Bristol",
    "Brodnica",
    "Browary",
    "Brzeg",
    "Bydgoszcz",
    "Bytom",
    "Chojnice",
    "Chorzów",
    "Ciechanów",
    "Cieszyn",
    "Częstochowa",
    "Działdowo",
    "Dąbrowa Górnicza",
    "Dęblin",
    "Ełk",
    "Garwolin",
    "Gdańsk",
    "Gdynia",
    "Giżycko",
    "Gliwice",
    "Gniezno",
    "Gorzów Wielkopolski",
    "Grudziądz",
    "Głogów",
    "Inowrocław",
    "Iława",
    "Jarocin",
    "Jarosław",
    "Jastrzębie-Zdrój",
    "Jasło",
    "Jaworzno",
    "Jelenia Góra",
    "Józefów",
    "Kalisz",
    "Kartuzy",
    "Katowice",
    "Kielce",
    "Konin",
    "Koszalin",
    "Kołobrzeg",
    "Kościerzyna",
    "Kraków",
    "Kwidzyn",
    "Kętrzyn",
    "Kłodzko",
    "Legnica",
    "Leszno",
    "Londyn",
    "Lubin",
    "Lublin",
    "Lębork",
    "Malbork",
    "Miechów",
    "Mińsk Mazowiecki",
    "Mysłowice",
    "Mława",
    "Nisko",
    "Nowy Sącz",
    "Nowy Targ",
    "Olkusz",
    "Olsztyn",
    "Opole",
    "Ostrołęka",
    "Ostrów Wielkopolski",
    "Oświęcim",
    "Piotrków Trybunalski",
    "Piła",
    "Pińczów",
    "Polkowice",
    "Poznań",
    "Przasnysz",
    "Puławy",
    "Pułtusk",
    "Płock",
    "Płońsk",
    "Radom",
    "Ruda Śląska",
    "Rybnik",
    "Rzeszów",
    "Sandomierz",
    "Sanok",
    "Siedlce",
    "Siemiatycze",
    "Sieradz",
    "Skoczów",
    "Sochaczew",
    "Sopot",
    "Sosnowiec",
    "Stalowa Wola",
    "Starogard Gdański",
    "Sucha Beskidzka",
    "Sulechów",
    "Suwałki",
    "Szczecin",
    "Szczecinek",
    "Słubice",
    "Słupsk",
    "Tarnobrzeg",
    "Tarnów",
    "Tczew",
    "Tomaszów Mazowiecki",
    "Toruń",
    "Trzcianka",
    "Tuchola",
    "Vsetin",
    "Warszawa",
    "Wałbrzych",
    "Wejherowo",
    "Wiedeń",
    "Wilno",
    "Wodzisław Śląski",
    "Wrocław",
    "Września",
    "Wyszków",
    "Wągrowiec",
    "Włocławek",
    "Zamość",
    "Zduńska Wola",
    "Zielona Góra",
    "Łomża",
    "Łódź",
    "Świdnica",
    "Świecie",
    "Żary",
    "Żywiec",
]
