SKILLS = [
    "archeologia",
    "nauki prawne",
    "nauki medyczne",
    "filozofia",
    "technologia żywności i żywienia",
    "literaturoznawstwo",
    "ekonomia i finanse",
    "stosunki międzynarodowe",
    "nauki o sztuce",
    "inżynieria lądowa i transport",
    "nauki chemiczne",
    "rolnictwo i ogrodnictwo",
    "nauki o polityce i administracji",
    "nauki o kulturze i religii",
    "nauki biologiczne",
    "automatyka, elektronika i elektrotechnika",
    "biologia medyczna",
    "prawo kanoniczne",
    "inżynieria materiałowa",
    "historia",
    "inżynieria chemiczna",
    "nauki o bezpieczeństwie",
    "nauki o Ziemi i środowisku",
    "zootechnika i rybactwo",
    "nauki fizyczne",
    "architektura i urbanistyka",
    "pedagogika",
    "nauki teologiczne",
    "inżynieria biomedyczna",
    "nauki o zarządzaniu i jakości",
    "matematyka",
    "geografia społeczno-ekonomiczna i gospodarka przestrzenna",
    "nauki socjologiczne",
    "językoznawstwo",
    "nauki o kulturze fizycznej",
    "astronomia",
    "sztuki muzyczne",
    "nauki o zdrowiu",
    "sztuki plastyczne i konserwacja dzieł sztuki",
    "weterynaria",
    "inżynieria bezpieczeństwa",
    "informatyka techniczna i telekomunikacja",
    "inżynieria mechaniczna",
    "psychologia",
    "inżynieria lądowa, geodezja i transport",
    "sztuki filmowe i teatralne",
    "inżynieria środowiska, górnictwo i energetyka",
    "nauki o komunikacji społecznej i mediach",
    "nauki leśne",
    "nauki farmaceutyczne",
    "informatyka",
    "biotechnologia",
    "automatyka, elektronika, elektrotechnika i technologie kosmiczne",
]


PROFESSIONS = [
    "Software Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Product Manager",
]

HOBBIES = [
    "Biking",
    "Hiking",
    "Swimming",
    "Running",
    "Reading",
    "Writing",
    "Drawing",
    "Painting",
]
